// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxdsimyktdxiogjuvids.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4ZHNpbXlrdGR4aW9nanV2aWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTIzMjcsImV4cCI6MjA3NDQ2ODMyN30.LT3fnuyRVH2EMVOsySQayzAIVN-etKQ1XxQFaHKjxwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});